version: "3"
services: 
  redis:
    image: "redis:alpine"
  web:
    build: .
    volumes:
     - .:/web

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static/meme.jpg:/www/media/static/meme.jpg
      - ./static/favicon.ico:/www/media/static/favicon.ico
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  db_data: {}